In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import zipfile

In [3]:
with zipfile.ZipFile('/content/house-prices-advanced-regression-techniques.zip') as primeira:
  print(*primeira.namelist(), sep='\n')

data_description.txt
sample_submission.csv
test.csv
train.csv

In [4]:
with zipfile.ZipFile('/content/house-prices-advanced-regression-techniques.zip') as primeira:
  with primeira.open('train.csv') as segunda:
    train = pd.read_csv(segunda)

In [5]:
with zipfile.ZipFile('/content/house-prices-advanced-regression-techniques.zip') as primeiratreino:
  with primeiratreino.open('test.csv') as segundotreino:
    test = pd.read_csv(segundotreino)

In [6]:
train.shape, test.shape

((1460, 81), (1459, 80))

In [7]:
train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [8]:
abacate = (train.isnull().sum())
print(abacate[abacate > 0])

LotFrontage      259
Alley           1369
MasVnrType         8
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

In [9]:
#de treino, dá para excluir alley, fireplacequ, poolqc, fence, miscfeature

In [10]:
abacaxi = (test.isnull().sum())
print(abacaxi[abacaxi > 0])

MSZoning           4
LotFrontage      227
Alley           1352
Utilities          2
Exterior1st        1
Exterior2nd        1
MasVnrType        16
MasVnrArea        15
BsmtQual          44
BsmtCond          45
BsmtExposure      44
BsmtFinType1      42
BsmtFinSF1         1
BsmtFinType2      42
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
BsmtFullBath       2
BsmtHalfBath       2
KitchenQual        1
Functional         2
FireplaceQu      730
GarageType        76
GarageYrBlt       78
GarageFinish      78
GarageCars         1
GarageArea         1
GarageQual        78
GarageCond        78
PoolQC          1456
Fence           1169
MiscFeature     1408
SaleType           1
dtype: int64

In [11]:
# de test:  Alley, FireplaceQu, PoolQC, Fence, MiscFeature

In [12]:
#acredito que dá para juntar os 2 dfs para limpar os dados de uma vez só.

In [13]:
df_completo = train.append(test, ignore_index = True)
df_completo

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2915,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2916,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2917,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2918,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [14]:
df_completo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2919 non-null   int64
 1   MSSubClass     2919 non-null   int64
 2   MSZoning       2915 non-null   object
 3   LotFrontage    2433 non-null   float64
 4   LotArea        2919 non-null   int64
 5   Street         2919 non-null   object
 6   Alley          198 non-null    object
 7   LotShape       2919 non-null   object
 8   LandContour    2919 non-null   object
 9   Utilities      2917 non-null   object
 10  LotConfig      2919 non-null   object
 11  LandSlope      2919 non-null   object
 12  Neighborhood   2919 non-null   object
 13  Condition1     2919 non-null   object
 14  Condition2     2919 non-null   object
 15  BldgType       2919 non-null   object
 16  HouseStyle     2919 non-null   object
 17  OverallQual    2919 non-null   int64
 18  OverallCond    2919 non-null   int64
 19  YearBuilt      2919 non-null   int64
 20  YearRemodAdd   2919 non-null   int64
 21  RoofStyle      2919 non-null   object
 22  RoofMatl       2919 non-null   object
 23  Exterior1st    2918 non-null   object
 24  Exterior2nd    2918 non-null   object
 25  MasVnrType     2895 non-null   object
 26  MasVnrArea     2896 non-null   float64
 27  ExterQual      2919 non-null   object
 28  ExterCond      2919 non-null   object
 29  Foundation     2919 non-null   object
 30  BsmtQual       2838 non-null   object
 31  BsmtCond       2837 non-null   object
 32  BsmtExposure   2837 non-null   object
 33  BsmtFinType1   2840 non-null   object
 34  BsmtFinSF1     2918 non-null   float64
 35  BsmtFinType2   2839 non-null   object
 36  BsmtFinSF2     2918 non-null   float64
 37  BsmtUnfSF      2918 non-null   float64
 38  TotalBsmtSF    2918 non-null   float64
 39  Heating        2919 non-null   object
 40  HeatingQC      2919 non-null   object
 41  CentralAir     2919 non-null   object
 42  Electrical     2918 non-null   object
 43  1stFlrSF       2919 non-null   int64
 44  2ndFlrSF       2919 non-null   int64
 45  LowQualFinSF   2919 non-null   int64
 46  GrLivArea      2919 non-null   int64
 47  BsmtFullBath   2917 non-null   float64
 48  BsmtHalfBath   2917 non-null   float64
 49  FullBath       2919 non-null   int64
 50  HalfBath       2919 non-null   int64
 51  BedroomAbvGr   2919 non-null   int64
 52  KitchenAbvGr   2919 non-null   int64
 53  KitchenQual    2918 non-null   object
 54  TotRmsAbvGrd   2919 non-null   int64
 55  Functional     2917 non-null   object
 56  Fireplaces     2919 non-null   int64
 57  FireplaceQu    1499 non-null   object
 58  GarageType     2762 non-null   object
 59  GarageYrBlt    2760 non-null   float64
 60  GarageFinish   2760 non-null   object
 61  GarageCars     2918 non-null   float64
 62  GarageArea     2918 non-null   float64
 63  GarageQual     2760 non-null   object
 64  GarageCond     2760 non-null   object
 65  PavedDrive     2919 non-null   object
 66  WoodDeckSF     2919 non-null   int64
 67  OpenPorchSF    2919 non-null   int64
 68  EnclosedPorch  2919 non-null   int64
 69  3SsnPorch      2919 non-null   int64
 70  ScreenPorch    2919 non-null   int64
 71  PoolArea       2919 non-null   int64
 72  PoolQC         10 non-null     object
 73  Fence          571 non-null    object
 74  MiscFeature    105 non-null    object
 75  MiscVal        2919 non-null   int64
 76  MoSold         2919 non-null   int64
 77  YrSold         2919 non-null   int64
 78  SaleType       2918 non-null   object
 79  SaleCondition  2919 non-null   object
 80  SalePrice      1460 non-null   float64
dtypes: float64(12), int64(26), object(43)
memory usage: 1.8+ MB

In [15]:
df_completo.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,2919.000000,2919.000000,2433.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2896.000000,2918.000000,...,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,1460.000000
mean,1460.000000,57.137718,69.305795,10168.114080,6.089072,5.564577,1971.312778,1984.264474,102.201312,441.423235,...,93.709832,47.486811,23.098321,2.602261,16.062350,2.251799,50.825968,6.213087,2007.792737,180921.195890
std,842.787043,42.517628,23.344905,7886.996359,1.409947,1.113131,30.291442,20.894344,179.334253,455.610826,...,126.526589,67.575493,64.244246,25.188169,56.184365,35.663946,567.402211,2.714762,1.314964,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,730.500000,20.000000,59.000000,7478.000000,5.000000,5.000000,1953.500000,1965.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129975.000000
50%,1460.000000,50.000000,68.000000,9453.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,368.500000,...,0.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,2189.500000,70.000000,80.000000,11570.000000,7.000000,6.000000,2001.000000,2004.000000,164.000000,733.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,2919.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [16]:
#2919 rows

In [17]:
apuracao = (df_completo.isnull().sum())
print(apuracao[apuracao > 0])

MSZoning           4
LotFrontage      486
Alley           2721
Utilities          2
Exterior1st        1
Exterior2nd        1
MasVnrType        24
MasVnrArea        23
BsmtQual          81
BsmtCond          82
BsmtExposure      82
BsmtFinType1      79
BsmtFinSF1         1
BsmtFinType2      80
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
Electrical         1
BsmtFullBath       2
BsmtHalfBath       2
KitchenQual        1
Functional         2
FireplaceQu     1420
GarageType       157
GarageYrBlt      159
GarageFinish     159
GarageCars         1
GarageArea         1
GarageQual       159
GarageCond       159
PoolQC          2909
Fence           2348
MiscFeature     2814
SaleType           1
SalePrice       1459
dtype: int64

In [18]:
df_completo.drop(['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature'], axis = 1, inplace = True)

In [19]:
apuracao = (df_completo.isnull().sum())
print(apuracao[apuracao > 0])

MSZoning           4
LotFrontage      486
Utilities          2
Exterior1st        1
Exterior2nd        1
MasVnrType        24
MasVnrArea        23
BsmtQual          81
BsmtCond          82
BsmtExposure      82
BsmtFinType1      79
BsmtFinSF1         1
BsmtFinType2      80
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
Electrical         1
BsmtFullBath       2
BsmtHalfBath       2
KitchenQual        1
Functional         2
GarageType       157
GarageYrBlt      159
GarageFinish     159
GarageCars         1
GarageArea         1
GarageQual       159
GarageCond       159
SaleType           1
SalePrice       1459
dtype: int64

In [20]:
df_completo['MSZoning'].isnull().sum()

4

In [21]:
df_completo.loc[df_completo['MSZoning'].isnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1915,1916,30,NaN,109.0,21780,Grvl,Reg,Lvl,NaN,Inside,...,0,0,0,0,0,3,2009,ConLD,Normal,NaN
2216,2217,20,NaN,80.0,14584,Pave,Reg,Low,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Abnorml,NaN
2250,2251,70,NaN,NaN,56600,Pave,IR1,Low,AllPub,Inside,...,0,0,0,0,0,1,2008,WD,Normal,NaN
2904,2905,20,NaN,125.0,31250,Pave,Reg,Lvl,AllPub,Inside,...,135,0,0,0,0,5,2006,WD,Normal,NaN

In [22]:
df_completo['MSZoning'].value_counts()

RL         2265
RM          460
FV          139
RH           26
C (all)      25
Name: MSZoning, dtype: int64

In [23]:
#forte tendência a ser "rl".
#buscar um padrão

In [24]:
df_completo['MSZoning'].fillna('RL', inplace = True)

In [25]:
df_completo['MSZoning'].isnull().sum()

0

In [26]:
df_completo.loc[df_completo['LotFrontage'].isnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
7,8,60,RL,NaN,10382,Pave,IR1,Lvl,AllPub,Corner,...,228,0,0,0,350,11,2009,WD,Normal,200000.0
12,13,20,RL,NaN,12968,Pave,IR2,Lvl,AllPub,Inside,...,0,0,176,0,0,9,2008,WD,Normal,144000.0
14,15,20,RL,NaN,10920,Pave,IR1,Lvl,AllPub,Corner,...,176,0,0,0,0,5,2008,WD,Normal,157000.0
16,17,20,RL,NaN,11241,Pave,IR1,Lvl,AllPub,CulDSac,...,0,0,0,0,700,3,2010,WD,Normal,149000.0
24,25,20,RL,NaN,8246,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,5,2010,WD,Normal,154000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2847,2848,20,RL,NaN,11088,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,0,0,6,2006,WD,Normal,NaN
2850,2851,60,RL,NaN,21533,Pave,IR2,Lvl,AllPub,FR2,...,0,0,0,0,0,8,2006,WD,Normal,NaN
2900,2901,20,RL,NaN,50102,Pave,IR1,Low,AllPub,Inside,...,0,0,138,0,0,3,2006,WD,Alloca,NaN
2901,2902,20,RL,NaN,8098,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,10,2006,WD,Normal,NaN
2908,2909,90,RL,NaN,11836,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,0,3,2006,WD,Normal,NaN

In [27]:
df_completo['LotFrontage'].fillna(df_completo['LotFrontage'].mean(), inplace = True)

In [28]:
df_completo['LotFrontage'].isnull().sum()

0

In [29]:
df_completo['Utilities'].value_counts()

AllPub    2916
NoSeWa       1
Name: Utilities, dtype: int64

In [30]:
df_completo['Utilities'].fillna('AllPub', inplace = True)

In [31]:
apuracao = (df_completo.isnull().sum())
print(apuracao[apuracao > 0])

Exterior1st        1
Exterior2nd        1
MasVnrType        24
MasVnrArea        23
BsmtQual          81
BsmtCond          82
BsmtExposure      82
BsmtFinType1      79
BsmtFinSF1         1
BsmtFinType2      80
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
Electrical         1
BsmtFullBath       2
BsmtHalfBath       2
KitchenQual        1
Functional         2
GarageType       157
GarageYrBlt      159
GarageFinish     159
GarageCars         1
GarageArea         1
GarageQual       159
GarageCond       159
SaleType           1
SalePrice       1459
dtype: int64

In [32]:
df_completo['Exterior1st'].value_counts()

VinylSd    1025
MetalSd     450
HdBoard     442
Wd Sdng     411
Plywood     221
CemntBd     126
BrkFace      87
WdShing      56
AsbShng      44
Stucco       43
BrkComm       6
AsphShn       2
Stone         2
CBlock        2
ImStucc       1
Name: Exterior1st, dtype: int64

In [33]:
df_completo['Exterior1st'].fillna('VinylSd', inplace = True)

In [34]:
df_completo['Exterior2nd'].value_counts()

VinylSd    1014
MetalSd     447
HdBoard     406
Wd Sdng     391
Plywood     270
CmentBd     126
Wd Shng      81
BrkFace      47
Stucco       47
AsbShng      38
Brk Cmn      22
ImStucc      15
Stone         6
AsphShn       4
CBlock        3
Other         1
Name: Exterior2nd, dtype: int64

In [35]:
df_completo['Exterior2nd'].fillna('VinylSd', inplace = True)

In [36]:
df_completo['MasVnrType'].value_counts()

None       1742
BrkFace     879
Stone       249
BrkCmn       25
Name: MasVnrType, dtype: int64

In [37]:
df_completo['MasVnrType'].isnull().sum()

24

In [38]:
df_completo['MasVnrType'].fillna('None', inplace = True)

In [39]:
df_completo['MasVnrArea'].value_counts()

0.0      1738
120.0      15
176.0      13
200.0      13
216.0      12
         ...
137.0       1
274.0       1
415.0       1
760.0       1
382.0       1
Name: MasVnrArea, Length: 444, dtype: int64

In [40]:
df_completo['MasVnrArea'].fillna(0.0, inplace = True)

In [41]:
df_completo['BsmtCond'].fillna('TA', inplace = True)

In [42]:
df_completo['BsmtQual'].value_counts()

TA    1283
Gd    1209
Ex     258
Fa      88
Name: BsmtQual, dtype: int64

In [43]:
df_completo['Foundation'].value_counts()

PConc     1308
CBlock    1235
BrkTil     311
Slab        49
Stone       11
Wood         5
Name: Foundation, dtype: int64

In [44]:
df_completo[df_completo['Foundation'] == 'PConc']['BsmtQual'].value_counts()

Gd    896
Ex    252
TA    139
Fa     13
Name: BsmtQual, dtype: int64

In [45]:
df_completo[df_completo['Foundation'] == 'CBlock']['BsmtQual'].value_counts()

TA    899
Gd    281
Fa     31
Ex      5
Name: BsmtQual, dtype: int64

In [46]:
pd.set_option('display.max_columns', 81)

In [47]:
df_completo['BsmtQual'][df_completo['Foundation'] == 'CBlock'].fillna('TA', inplace = True)

In [48]:
df_completo.loc[df_completo['BsmtQual'].isnull()][df_completo['Foundation'] == 'CBlock'].fillna('TA', inplace = True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [49]:
df_completo['BsmtQual'].isnull().sum()

81

In [50]:
df_completo[df_completo['BsmtQual'] == 'TA']['Foundation'].value_counts()

CBlock    899
BrkTil    238
PConc     139
Stone       7
Name: Foundation, dtype: int64

In [51]:
df_completo[df_completo['BsmtQual'] == 'Gd']['Foundation'].value_counts()

PConc     896
CBlock    281
BrkTil     27
Wood        5
Name: Foundation, dtype: int64

In [52]:
df_completo[df_completo['BsmtQual'] == 'Ex']['Foundation'].value_counts()

PConc     252
CBlock      5
BrkTil      1
Name: Foundation, dtype: int64

In [53]:
df_completo[df_completo['BsmtQual'] == 'Fa']['Foundation'].value_counts()

BrkTil    41
CBlock    31
PConc     13
Stone      3
Name: Foundation, dtype: int64

In [54]:
df_completo[(df_completo['BsmtQual'] != 'Fa') & (df_completo['BsmtQual'] != 'Ex') & (df_completo['BsmtQual'] != 'Gd') & (df_completo['BsmtQual'] != 'TA')]['Foundation'].value_counts()

Slab      49
CBlock    19
PConc      8
BrkTil     4
Stone      1
Name: Foundation, dtype: int64

In [55]:
#deu pra ver que, em 'BsmtQual', os valores tinham como "Foundation" PConc e CBlock
#sendo pconc com tendencia para gd e Clobck para ta
#sobre os valores nulos, a maioria tinha como resposta para "Foundation" slab e, em segundo cblcok, segundo por pconc, brktil e stone por último

In [56]:
df_completo['Foundation'].unique()

array(['PConc', 'CBlock', 'BrkTil', 'Wood', 'Slab', 'Stone'], dtype=object)

In [57]:
df_completo[df_completo['Foundation'] == 'Slab']

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
17,18,90,RL,72.000000,10791,Pave,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,Norm,Norm,Duplex,1Story,4,5,1967,1967,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1296,0,0,1296,0.0,0.0,2,0,2,2,TA,6,Typ,0,CarPort,1967.0,Unf,2.0,516.0,TA,TA,Y,0,0,0,0,0,0,500,10,2006,WD,Normal,90000.0
90,91,20,RL,60.000000,7200,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,4,5,1950,1950,Gable,CompShg,BrkFace,Wd Sdng,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,FuseA,1040,0,0,1040,0.0,0.0,1,0,2,1,TA,4,Typ,0,Detchd,1950.0,Unf,2.0,420.0,TA,TA,Y,0,29,0,0,0,0,0,7,2006,WD,Normal,109900.0
102,103,90,RL,64.000000,7018,Pave,Reg,Bnk,AllPub,Inside,Gtl,SawyerW,Norm,Norm,Duplex,1Story,5,5,1979,1979,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,Fa,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1535,0,0,1535,0.0,0.0,2,0,4,2,TA,8,Typ,0,Attchd,1979.0,Unf,2.0,410.0,TA,TA,Y,0,0,0,0,0,0,0,6,2009,WD,Alloca,118964.0
342,343,90,RL,69.305795,8544,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,Duplex,1Story,3,4,1949,1950,Gable,CompShg,Stucco,Stucco,BrkFace,340.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,Wall,Fa,N,FuseA,1040,0,0,1040,0.0,0.0,2,0,2,2,TA,6,Typ,0,Detchd,1949.0,Unf,2.0,400.0,TA,TA,Y,0,0,0,0,0,0,0,5,2006,WD,Normal,87500.0
362,363,85,RL,64.000000,7301,Pave,Reg,Lvl,AllPub,Corner,Gtl,Edwards,Norm,Norm,1Fam,SFoyer,7,5,2003,2003,Gable,CompShg,HdBoard,HdBoard,BrkFace,500.0,Gd,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Ex,Y,SBrkr,495,1427,0,1922,0.0,0.0,3,0,4,1,Gd,7,Typ,1,BuiltIn,2003.0,RFn,2.0,672.0,TA,TA,Y,0,0,177,0,0,0,0,7,2009,ConLD,Normal,198500.0
392,393,20,RL,69.305795,8339,Pave,IR1,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,7,1959,1959,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,882,0,0,882,0.0,0.0,1,0,3,1,TA,5,Typ,0,Attchd,1959.0,RFn,1.0,294.0,TA,TA,Y,0,0,0,0,0,0,1200,7,2007,WD,Normal,106500.0
532,533,20,RL,60.000000,7200,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,7,1955,2007,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Ex,Y,SBrkr,827,0,0,827,0.0,0.0,1,0,2,1,TA,5,Mod,1,Detchd,1967.0,Unf,1.0,392.0,TA,TA,Y,0,0,0,0,0,0,0,4,2010,WD,Normal,107500.0
533,534,20,RL,50.000000,5000,Pave,Reg,Low,AllPub,Inside,Mod,BrkSide,Norm,Norm,1Fam,1Story,1,3,1946,1950,Gable,CompShg,VinylSd,VinylSd,None,0.0,Fa,Fa,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Fa,N,FuseF,334,0,0,334,0.0,0.0,1,0,1,1,Fa,2,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,0,0,0,0,0,1,2007,WD,Normal,39300.0
705,706,190,RM,70.000000,5600,Pave,Reg,Lvl,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,2fmCon,2Story,4,5,1930,1950,Hip,CompShg,VinylSd,Wd Shng,None,0.0,Fa,Fa,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Fa,N,SBrkr,372,720,0,1092,0.0,0.0,2,0,3,2,Fa,7,Mod,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,0,0,0,0,3500,7,2010,WD,Normal,55000.0
749,750,50,RL,50.000000,8405,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1.5Fin,4,3,1945,1950,Gable,CompShg,WdShing,Wd Shng,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,Wall,TA,N,FuseF,1088,441,0,1529,0.0,0.0,2,0,4,1,TA,9,Mod,0,Detchd,1945.0,Unf,1.0,240.0,TA,TA,N,92,0,185,0,0,0,0,4,2009,WD,Normal,98000.0
778,779,90,RH,60.000000,8400,Pave,Reg,Lvl,AllPub,Inside,Gtl,SawyerW,Feedr,Norm,Duplex,1Story,5,5,1977,1977,Gable,CompShg,Plywood,Plywood,BrkFace,320.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,2020,0,0,2020,0.0,0.0,2,0,4,2,TA,10,Typ,2,Detchd,1977.0,Unf,2.0,630.0,TA,TA,Y,0,0,0,0,0,0,0,10,2007,WD,Normal,144000.0
868,869,60,RL,69.305795,14762,Pave,IR2,Lvl,AllPub,Corner,Gtl,Gilbert,Feedr,Norm,1Fam,2Story,5,6,1948,1950,Gable,CompShg,Plywood,Plywood,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Gd,Y,SBrkr,1547,720,53,2320,0.0,0.0,2,0,2,1,TA,7,Typ,1,Attchd,1979.0,Unf,2.0,672.0,TA,TA,P,120,144,0,0,0,0,0,5,2006,WD,Normal,169000.0
894,895,90,RL,64.000000,7018,Pave,Reg,Bnk,AllPub,Inside,Gtl,SawyerW,Norm,Norm,Duplex,1Story,5,5,1979,1979,Gable,CompShg,Plywood,Plywood,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1535,0,0,1535,0.0,0.0,2,0,4,2,TA,8,Typ,0,Attchd,1979.0,Unf,2.0,400.0,TA,TA,Y,0,0,0,0,0,0,0,6,2009,WD,Alloca,118858.0
897,898,90,RL,64.000000,7018,Pave,Reg,Lvl,AllPub,Inside,Gtl,SawyerW,Feedr,Norm,Duplex,2Story,5,5,1979,1979,Gable,CompShg,Plywood,Plywood,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1120,1120,0,2240,0.0,0.0,2,0,6,2,TA,12,Typ,0,Detchd,1979.0,Unf,2.0,528.0,TA,TA,Y,154,0,0,0,0,0,0,6,2009,WD,Alloca,142953.0
1000,1001,20,RL,74.000000,10206,Pave,Reg,Lvl,AllPub,Corner,Gtl,Edwards,Norm,Norm,1Fam,1Story,3,3,1952,1952,Flat,Tar&Grv,BrkComm,Brk Cmn,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasW,Fa,N,FuseF,944,0,0,944,0.0,0.0,1,0,2,1,Fa,4,Min1,0,Detchd,1956.0,Unf,2.0,528.0,TA,Fa,Y,0,0,0,0,0,0,0,7,2009,WD,Normal,82000.0
1035,1036,20,RL,69.305795,11500,Pave,IR1,Lvl,AllPub,CulDSac,Gtl,Edwards,Norm,Norm,1Fam,1Story,4,3,1957,1957,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,TA,Gd,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Ex,N,SBrkr,845,0,0,845,0.0,0.0,1,0,3,1,TA,5,Typ,0,Detchd,1957.0,Unf,1.0,290.0,TA,TA,N,186,0,0,0,0,0,0,1,2009,WD,Normal,84000.0
1045,1046,20,RL,69.305795,13680,Pave,IR1,Lvl,AllPub,CulDSac,Gtl,Edwards,Norm,Norm,1Fam,1Story,3,5,1955,1955,Hip,CompShg,BrkFace,Wd Sdng,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Ex,Y,FuseA,1733,0,0,1733,0.0,0.0,2,0,4,1,TA,8,Min2,1,Attchd,1955.0,Unf,2.0,452.0,TA,TA,Y,0,0,0,0,0,0,0,6,2009,WD,Normal,139600.0
1048,1049,20,RL,100.000000,21750,Pave,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,1Story,5,4,1960,2006,Hip,CompShg,HdBoard,HdBoard,BrkFace,75.0,TA,Fa,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1771,0,0,1771,0.0,0.0,1,0,3,1,TA,9,Min1,1,Attchd,1960.0,Unf,2.0,336.0,TA,TA,Y,0,0,0,0,0,0,0,11,2009,WD,Normal,115000.0
1090,1091,90,RL,60.000000,8544,Pave,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,Duplex,1Story,3,4,1950,1950,Gable,CompShg,BrkFace,BrkFace,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,Wall,Fa,N,FuseA,1040,0,0,1040,0.0,0.0,2,0,2,2,TA,6,Typ,0,Detchd,1987.0,Unf,2.0,400.0,TA,TA,Y,0,0,0,0,0,0,0,6,2009,WD,Normal,92900.0
1179,1180,20,RL,77.000000,8335,Pave,Reg,Lvl,AllPub,Corner,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,5,1954,1954,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Gd,Y,SBrkr,1124,0,0,1124,0.0,0.0,1,0,3,1,TA,5,Min2,1,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,36,190,0,0,0,0,4,2006,WD,Normal,93000.0
1216,1217,90,RM,68.000000,8930,Pave,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,RRAe,Norm,Duplex,1.5Fin,6,5,1978,1978,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1318,584,0,1902,0.0,0.0,2,0,4,2,TA,8,Typ,0,Attchd,1978.0,Unf,2.0,539.0,TA,TA,Y,0,0,0,0,0,0,0,4,2010,WD,Normal,112000.0
1218,1219,50,RM,52.000000,6240,Pave,Reg,Lvl,AllPub,Inside,Gtl,BrkSide,Norm,Norm,1Fam,1.5Fin,4,5,1947,1950,Gable,CompShg,AsbShng,AsbShng,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Gd,N,SBrkr,672,240,0,912,0.0,0.0,1,0,2,1,TA,3,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,0,0,0,0,0,7,2006,WD,Normal,80500.0
1232,1233,90,RL,70.000000,9842,Pave,Reg,Lvl,AllPub,FR2,Gtl,NAmes,Norm,Norm,Duplex,1Story,4,5,1962,1962,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1224,0,0,1224,0.0,0.0,2,0,2,2,TA,6,Typ,0,CarPort,1962.0,Unf,2.0,462.0,TA,TA,Y,0,0,0,0,0,0,0,3,2007,WD,Normal,101800.0
1412,1413,90,RL,60.000000,7200,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,Duplex,1Story,4,5,1949,1950,Gable,CompShg,BrkFace,Stone,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,Wall,Fa,N,FuseF,1040,0,0,1040,0.0,0.0,2,0,2,2,TA,6,Typ,0,Detchd,1956.0,Unf,2.0,420.0,TA,TA,Y,0,0,0,0,0,0,0,6,2009,WD,Normal,90000.0
1593,1594,90,RH,60.000000,7200,Pave,Reg,Lvl,AllPub,Inside,Gtl,SWISU,Norm,Norm,Duplex,2Story,4,6,1967,1967,Flat,Tar&Grv,Plywood,CBlock,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,862,1788,0,2650,0.0,0.0,3,0,6,2,TA,10,Min2,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,0,0,0,0,0,500,2,2010,WD,Normal,NaN
1729,1730,90,RL,75.000000,8250,Pave,Reg,Lvl,AllPub,Inside,Gtl,SawyerW,Norm,Norm,Duplex,2Story,6,7,1981,1981,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,964,918,0,1882,0.0,0.0,2,0,4,2,TA,8,Typ,2,Attchd,1981.0,Unf,2.0,612.0,TA,TA,Y,0,0,0,0,0,0,0,5,2009,WD,Normal,NaN
1778,1779,20,RL,75.000000,9533,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,5,1953,1953,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,140.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,FuseA,1210,0,0,1210,0.0,0.0,1,1,2,1,TA,7,Typ,0,Attchd,1953.0,Fin,1.0,616.0,TA,TA,Y,208,0,100,0,0,0,0,8,2009,ConLD,Normal,NaN
1847,1848,20,RL,69.305795,9000,Pave,Reg,Lvl,AllPub,Corner,Gtl,Sawyer,Norm,Norm,1Fam,1Story,2,2,1947,1950,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Fa,N,SBrkr,660,0,0,660,0.0,0.0,1,0,2,1,Fa,5,Min2,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,100,0,0,0,0,6,2009,WD,Normal,NaN
1857,1858,90,RL,64.000000,7018,Pave,Reg,Lvl,AllPub,Inside,Gtl,SawyerW,Feedr,Norm,Duplex,2Story,5,5,1979,1979,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1114,1114,0,2228,0.0,0.0,2,0,6,2,TA,8,Typ,0,Detchd,1979.0,Unf,2.0,720.0,TA,TA,Y,73,0,0,0,0,0,0,6,2009,WD,Alloca,NaN
1858,1859,90,RL,64.000000,7018,Pave,Reg,Bnk,AllPub,Inside,Gtl,SawyerW,Norm,Norm,Duplex,1Story,5,5,1979,1979,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1535,0,0,1535,0.0,0.0,2,0,4,2,TA,8,Typ,0,Attchd,1979.0,Unf,2.0,400.0,TA,TA,Y,0,0,0,0,0,0,0,6,2009,WD,Alloca,NaN
1860,1861,90,RL,64.000000,7007,Pave,Reg,Bnk,AllPub,Inside,Gtl,SawyerW,Norm,Norm,Duplex,1Story,5,5,1979,1979,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1513,0,0,1513,0.0,0.0,2,0,4,2,TA,8,Typ,0,Attchd,1979.0,Unf,2.0,400.0,TA,TA,Y,0,0,0,0,0,0,0,6,2009,WD,Alloca,NaN
2050,2051,20,RL,74.000000,7785,Pave,IR1,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,5,1956,1956,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1014,0,0,1014,0.0,0.0,1,0,2,1,TA,6,Typ,0,Attchd,1956.0,RFn,1.0,267.0,TA,TA,Y,0,0,40,0,200,0,0,3,2008,WD,Normal,NaN
2068,2069,20,RL,60.000000,10122,Pave,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,1Fam,1Story,4,6,1948,1950,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,N,SBrkr,869,0,0,869,0.0,0.0,1,0,1,1,TA,3,Typ,0,Detchd,1948.0,Unf,1.0,390.0,Fa,TA,N,0,0,66,0,0,0,0,8,2008,WD,Normal,NaN
2188,2189,20,RL,123.000000,47007,Pave,IR1,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,7,1959,1996,Gable,CompShg,Plywood,Plywood,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,3820,0,0,3820,NaN,NaN,3,1,5,1,Ex,11,Typ,2,Attchd,1959.0,Unf,2.0,624.0,TA,TA,Y,0,372,0,0,0,0,0,7,2008,WD,Normal,NaN
2190,2191,90,RL,74.000000,6845,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,Duplex,1Story,4,5,1955,1955,Gable,CompShg,WdShing,Wd Shng,BrkCmn,58.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,N,FuseF,1152,0,0,1152,0.0,0.0,2,0,2,2,TA,6,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,0,0,0,0,0,7,2008,WD,Normal,NaN
2193,2194,50,RL,57.000000,8050,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1.5Fin,5,8,1947,1993,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,Gd,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Gd,Y,SBrkr,929,208,0,1137,0.0,0.0,1,1,4,1,TA,8,Min1,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,0,0,0,0,0,0,4,2008,WD,Normal,NaN
2216,2217,20,RL,80.000000,14584,Pave,Reg,Low,AllPub,Inside,Mod,IDOTRR,Norm,Norm,1Fam,1Story,1,5,1952,1952,Gable,CompShg,AsbShng,VinylSd,None,0.0,Fa,Po,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,Wall,Po,N,FuseA,733,0,0,733,0.0,0.0,1,0,2,1,Fa,4,NaN,0,Attchd,1952.0,Unf,2.0,487.0,Fa,Po,N,0,0,0,0,0,0,0,2,2008,WD,Abnorml,NaN
2387,2388,90,RL,69.305795,10899,Pave,IR1,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,Duplex,1Story,4,5,1964,1964,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,N,SBrkr,1224,0,0,1224,0.0,0.0,2,0,2,2,TA,8,Typ,0,CarPort,1964.0,Unf,3.0,530.0,TA,TA,Y,0,0,0,0,0,0,0,4,2007,WD,Normal,NaN
2435,2436,20,RL,70.000000,7000,Pave,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,BrkFace,Wd Sdng,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Gd,Y,SBrkr,925,0,0,925,0.0,0.0,1,0,3,1,TA,7,Typ,0,Attchd,1961.0,Fin,1.0,300.0,TA,TA,Y,0,0,0,0,0,0,0,7,2007,WD,Normal,NaN
2453,2454,80,RM,76.000000,11800,Pave,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,1Fam,SLvl,4,7,1949,2002,Gable,CompShg,Stucco,Wd Sdng,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Ex,Y,SBrkr,1382,0,0,1382,0.0,0.0,2,0,1,1,TA,6,Mod,1,Attchd,1957.0,RFn,1.0,384.0,TA,TA,Y,0,40,0,0,0,0,0,5,2007,WD,Normal,NaN
2490,2491,20,RL,69.305795,9000,Pave,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,Norm,Norm,1Fam,1Story,4,7,1945,1950,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,Fa,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,N,FuseA,998,0,0,998,0.0,0.0,1,0,3,1,TA,5,Min2,0,2Types,1952.0,Unf,2.0,460.0,Fa,TA,Y,0,0,140,0,0,0,0,5,2007,WD,Normal,NaN
2498,2499,30,RL,69.305795,11515,Pave,IR1,Lvl,AllPub,CulDSac,Gtl,Edwards,Norm,Norm,1Fam,1Story,4,5,1958,1994,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,N,SBrkr,943,0,0,943,0.0,0.0,1,0,3,1,Gd,5,Min2,0,Detchd,1958.0,Unf,1.0,308.0,TA,TA,N,0,0,60,0,0,0,0,8,2007,WD,Normal,NaN
2547,2548,90,RL,69.305795,9555,Pave,IR1,Lvl,AllPub,CulDSac,Gtl,Edwards,Norm,Norm,Duplex,2Story,5,6,1979,1979,Gable,CompShg,Plywood,Plywood,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1100,1133,0,2233,0.0,0.0,2,1,5,2,TA,11,Typ,0,Attchd,1979.0,Fin,2.0,579.0,TA,Gd,Y,0,0,0,0,0,0,0,2,2007,WD,Normal,NaN
2763,2764,20,RL,86.000000,11650,Pave,Reg,Lvl,AllPub,Corner,Gtl,NAmes,PosA,Norm,1Fam,1Story,7,5,1959,1959,Hip,CompShg,Plywood,Plywood,BrkCmn,58.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Gd,Y,FuseA,1472,0,0,1472,0.0,0.0,2,0,2,1,Gd,5,Typ,1,Attchd,1959.0,Unf,2.0,484.0,TA,TA,Y,0,68,0,0,227,0,0,6,2006,WD,Normal,NaN
2766,2767,90,RL,60.000000,8544,Pave,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,Duplex,1Story,3,4,1950,1950,Gable,CompShg,BrkFace,Stone,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,Wall,Fa,N,FuseF,1040,0,0,1040,0.0,0.0,2,0,2,2,TA,6,Typ,0,Detchd,1950.0,Unf,2.0,400.0,TA,Fa,Y,0,0,0,0,0,0,0,12,2006,WD,Normal,NaN
2803,2804,20,RL,100.000000,21370,Pave,Reg,Lvl,AllPub,FR2,Gtl,Sawyer,Norm,Norm,1Fam,1Story,5,5,1950,1950,Gable,CompShg,Wd Sdng,MetalSd,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,FuseA,1640,0,0,1640,0.0,0.0,1,0,3,1,TA,7,Min1,1,Attchd,1950.0,RFn,2.0,394.0,TA,TA,Y,0,0,225,0,0,0,600,6,2006,WD,Normal,NaN
2804,2805,30,RL,55.000000,8250,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,7,1935,1950,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,N,SBrkr,1032,0,0,1032,0.0,0.0,1,0,2,1,TA,6,Typ,1,Detchd,1939.0,Unf,1.0,260.0,TA,TA,Y,0,0,121,0,0,0,0,6,2006,WD,Normal,NaN
2824,2825,20,RL,80.000000,12048,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,6,1952,2002,Gable,CompShg,Wd Sdng,Wd Sdng,BrkFace,232.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,Gd,Y,SBrkr,1488,0,0,1488,0.0,0.0,1,0,3,1,TA,7,Typ,1,Attchd,2002.0,RFn,2.0,569.0,TA,TA,Y,0,189,36,0,348,0,0,4,2006,WD,Normal,NaN
2891,2892,30,C (all),69.000000,12366,Pave,Reg,Lvl,AllPub,Inside,Gtl,IDOTRR,Feedr,Norm,1Fam,1Story,3,5,1945,1950,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,TA,TA,Slab,NaN,TA,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,N,SBrkr,729,0,0,729,0.0,0.0,1,0,2,1,TA,5,Mod,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,23,0,0,0,0,10,2006,WD,Abnorml,NaN

In [64]:
df_completo['BsmtQual'].fillna('TA', inplace = True)

In [67]:
abacate = df_completo.isnull().sum()
print(abacate[abacate>0])

BsmtExposure      82
BsmtFinType1      79
BsmtFinSF1         1
BsmtFinType2      80
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
Electrical         1
BsmtFullBath       2
BsmtHalfBath       2
KitchenQual        1
Functional         2
GarageType       157
GarageYrBlt      159
GarageFinish     159
GarageCars         1
GarageArea         1
GarageQual       159
GarageCond       159
SaleType           1
SalePrice       1459
dtype: int64

In [70]:
df_completo['BsmtExposure'].unique()

array(['No', 'Gd', 'Mn', 'Av', nan], dtype=object)

In [71]:
df_completo['BsmtExposure'].value_counts()

No    1904
Av     418
Gd     276
Mn     239
Name: BsmtExposure, dtype: int64

In [75]:
def relatorio(dataframe, coluna):
  print(f'Quantidade de valores únicos: {dataframe[coluna].nunique()}')
  print(f'Quem são esses valores únicos: {dataframe[coluna].unique()}')
  print(f'Os valores únicos: {dataframe[coluna].isnull().sum()}')
  print(f'Como é a distribuição: \n{dataframe[coluna].value_counts()}')

In [76]:
relatorio(df_completo, 'BsmtExposure')

Quantidade de valores únicos: 4
Quem são esses valores únicos: ['No' 'Gd' 'Mn' 'Av' nan]
Os valores únicos: 82
Como é a distribuição:
No    1904
Av     418
Gd     276
Mn     239
Name: BsmtExposure, dtype: int64

In [77]:
df_completo['BsmtExposure'].fillna('No', inplace = True)

In [78]:
relatorio(df_completo, 'BsmtFinType1')

Quantidade de valores únicos: 6
Quem são esses valores únicos: ['GLQ' 'ALQ' 'Unf' 'Rec' 'BLQ' nan 'LwQ']
Os valores únicos: 79
Como é a distribuição:
Unf    851
GLQ    849
ALQ    429
Rec    288
BLQ    269
LwQ    154
Name: BsmtFinType1, dtype: int64

In [119]:
df_completo[df_completo['BsmtFinType1'] == 'Unf']['MasVnrType'].value_counts()

None       616
BrkFace    166
Stone       66
BrkCmn       3
Name: MasVnrType, dtype: int64

In [120]:
df_completo[df_completo['BsmtFinType1'] == 'GLQ']['MasVnrType'].value_counts()

BrkFace    371
None       340
Stone      137
BrkCmn       1
Name: MasVnrType, dtype: int64

In [126]:
#pensar mais a frente em uma solução

In [128]:
relatorio(df_completo, 'BsmtFinSF1')

Quantidade de valores únicos: 991
Quem são esses valores únicos: [7.060e+02 9.780e+02 4.860e+02 2.160e+02 6.550e+02 7.320e+02 1.369e+03
 8.590e+02 0.000e+00 8.510e+02 9.060e+02 9.980e+02 7.370e+02 7.330e+02
 5.780e+02 6.460e+02 5.040e+02 8.400e+02 1.880e+02 2.340e+02 1.218e+03
 1.277e+03 1.018e+03 1.153e+03 1.213e+03 7.310e+02 6.430e+02 9.670e+02
 7.470e+02 2.800e+02 1.790e+02 4.560e+02 1.351e+03 2.400e+01 7.630e+02
 1.820e+02 1.040e+02 1.810e+03 3.840e+02 4.900e+02 6.490e+02 6.320e+02
 9.410e+02 7.390e+02 9.120e+02 1.013e+03 6.030e+02 1.880e+03 5.650e+02
 3.200e+02 4.620e+02 2.280e+02 3.360e+02 4.480e+02 1.201e+03 3.300e+01
 5.880e+02 6.000e+02 7.130e+02 1.046e+03 6.480e+02 3.100e+02 1.162e+03
 5.200e+02 1.080e+02 5.690e+02 1.200e+03 2.240e+02 7.050e+02 4.440e+02
 2.500e+02 9.840e+02 3.500e+01 7.740e+02 4.190e+02 1.700e+02 1.470e+03
 9.380e+02 5.700e+02 3.000e+02 1.200e+02 1.160e+02 5.120e+02 5.670e+02
 4.450e+02 6.950e+02 4.050e+02 1.005e+03 6.680e+02 8.210e+02 4.320e+02
 1.300e+03 5.070e+02 6.790e+02 1.332e+03 2.090e+02 6.800e+02 7.160e+02
 1.400e+03 4.160e+02 4.290e+02 2.220e+02 5.700e+01 6.600e+02 1.016e+03
 3.700e+02 3.510e+02 3.790e+02 1.288e+03 3.600e+02 6.390e+02 4.950e+02
 2.880e+02 1.398e+03 4.770e+02 8.310e+02 1.904e+03 4.360e+02 3.520e+02
 6.110e+02 1.086e+03 2.970e+02 6.260e+02 5.600e+02 3.900e+02 5.660e+02
 1.126e+03 1.036e+03 1.088e+03 6.410e+02 6.170e+02 6.620e+02 3.120e+02
 1.065e+03 7.870e+02 4.680e+02 3.600e+01 8.220e+02 3.780e+02 9.460e+02
 3.410e+02 1.600e+01 5.500e+02 5.240e+02 5.600e+01 3.210e+02 8.420e+02
 6.890e+02 6.250e+02 3.580e+02 4.020e+02 9.400e+01 1.078e+03 3.290e+02
 9.290e+02 6.970e+02 1.573e+03 2.700e+02 9.220e+02 5.030e+02 1.334e+03
 3.610e+02 6.720e+02 5.060e+02 7.140e+02 4.030e+02 7.510e+02 2.260e+02
 6.200e+02 5.460e+02 3.920e+02 4.210e+02 9.050e+02 9.040e+02 4.300e+02
 6.140e+02 4.500e+02 2.100e+02 2.920e+02 7.950e+02 1.285e+03 8.190e+02
 4.200e+02 8.410e+02 2.810e+02 8.940e+02 1.464e+03 7.000e+02 2.620e+02
 1.274e+03 5.180e+02 1.236e+03 4.250e+02 6.920e+02 9.870e+02 9.700e+02
 2.800e+01 2.560e+02 1.619e+03 4.000e+01 8.460e+02 1.124e+03 7.200e+02
 8.280e+02 1.249e+03 8.100e+02 2.130e+02 5.850e+02 1.290e+02 4.980e+02
 1.270e+03 5.730e+02 1.410e+03 1.082e+03 2.360e+02 3.880e+02 3.340e+02
 8.740e+02 9.560e+02 7.730e+02 3.990e+02 1.620e+02 7.120e+02 6.090e+02
 3.710e+02 5.400e+02 7.200e+01 6.230e+02 4.280e+02 3.500e+02 2.980e+02
 1.445e+03 2.180e+02 9.850e+02 6.310e+02 1.280e+03 2.410e+02 6.900e+02
 2.660e+02 7.770e+02 8.120e+02 7.860e+02 1.116e+03 7.890e+02 1.056e+03
 5.000e+01 1.128e+03 7.750e+02 1.309e+03 1.246e+03 9.860e+02 6.160e+02
 1.518e+03 6.640e+02 3.870e+02 4.710e+02 3.850e+02 3.650e+02 1.767e+03
 1.330e+02 6.420e+02 2.470e+02 3.310e+02 7.420e+02 1.606e+03 9.160e+02
 1.850e+02 5.440e+02 5.530e+02 3.260e+02 7.780e+02 3.860e+02 4.260e+02
 3.680e+02 4.590e+02 1.350e+03 1.196e+03 6.300e+02 9.940e+02 1.680e+02
 1.261e+03 1.567e+03 2.990e+02 8.970e+02 6.070e+02 8.360e+02 5.150e+02
 3.740e+02 1.231e+03 1.110e+02 3.560e+02 4.000e+02 6.980e+02 1.247e+03
 2.570e+02 3.800e+02 2.700e+01 1.410e+02 9.910e+02 6.500e+02 5.210e+02
 1.436e+03 2.260e+03 7.190e+02 3.770e+02 1.330e+03 3.480e+02 1.219e+03
 7.830e+02 9.690e+02 6.730e+02 1.358e+03 1.260e+03 1.440e+02 5.840e+02
 5.540e+02 1.002e+03 6.190e+02 1.800e+02 5.590e+02 3.080e+02 8.660e+02
 8.950e+02 6.370e+02 6.040e+02 1.302e+03 1.071e+03 2.900e+02 7.280e+02
 2.000e+00 1.441e+03 9.430e+02 2.310e+02 4.140e+02 3.490e+02 4.420e+02
 3.280e+02 5.940e+02 8.160e+02 1.460e+03 1.324e+03 1.338e+03 6.850e+02
 1.422e+03 1.283e+03 8.100e+01 4.540e+02 9.030e+02 6.050e+02 9.900e+02
 2.060e+02 1.500e+02 4.570e+02 4.800e+01 8.710e+02 4.100e+01 6.740e+02
 6.240e+02 4.800e+02 1.154e+03 7.380e+02 4.930e+02 1.121e+03 2.820e+02
 5.000e+02 1.310e+02 1.696e+03 8.060e+02 1.361e+03 9.200e+02 1.721e+03
 1.870e+02 1.138e+03 9.880e+02 1.930e+02 5.510e+02 7.670e+02 1.186e+03
 8.920e+02 3.110e+02 8.270e+02 5.430e+02 1.003e+03 1.059e+03 2.390e+02
 9.450e+02 2.000e+01 1.455e+03 9.650e+02 9.800e+02 8.630e+02 5.330e+02
 1.084e+03 1.173e+03 5.230e+02 1.148e+03 1.910e+02 1.234e+03 3.750e+02
 8.080e+02 7.240e+02 1.520e+02 1.180e+03 2.520e+02 8.320e+02 5.750e+02
 9.190e+02 4.390e+02 3.810e+02 4.380e+02 5.490e+02 6.120e+02 1.163e+03
 4.370e+02 3.940e+02 1.416e+03 4.220e+02 7.620e+02 9.750e+02 1.097e+03
 2.510e+02 6.860e+02 6.560e+02 5.680e+02 5.390e+02 8.620e+02 1.970e+02
 5.160e+02 6.630e+02 6.080e+02 1.636e+03 7.840e+02 2.490e+02 1.040e+03
 4.830e+02 1.960e+02 5.720e+02 3.380e+02 3.300e+02 1.560e+02 1.390e+03
 5.130e+02 4.600e+02 6.590e+02 3.640e+02 5.640e+02 3.060e+02 5.050e+02
 9.320e+02 7.500e+02 6.400e+01 6.330e+02 1.170e+03 8.990e+02 9.020e+02
 1.238e+03 5.280e+02 1.024e+03 1.064e+03 2.850e+02 2.188e+03 4.650e+02
 3.220e+02 8.600e+02 5.990e+02 3.540e+02 6.300e+01 2.230e+02 3.010e+02
 4.430e+02 4.890e+02 2.840e+02 2.940e+02 8.140e+02 1.650e+02 5.520e+02
 8.330e+02 4.640e+02 9.360e+02 7.720e+02 1.440e+03 7.480e+02 9.820e+02
 3.980e+02 5.620e+02 4.840e+02 4.170e+02 6.990e+02 6.960e+02 8.960e+02
 5.560e+02 1.106e+03 6.510e+02 8.670e+02 8.540e+02 1.646e+03 1.074e+03
 5.360e+02 1.172e+03 9.150e+02 5.950e+02 1.237e+03 2.730e+02 6.840e+02
 3.240e+02 1.165e+03 1.380e+02 1.513e+03 3.170e+02 1.012e+03 1.022e+03
 5.090e+02 9.000e+02 1.085e+03 1.104e+03 2.400e+02 3.830e+02 6.440e+02
 3.970e+02 7.400e+02 8.370e+02 2.200e+02 5.860e+02 5.350e+02 4.100e+02
 7.500e+01 8.240e+02 5.920e+02 1.039e+03 5.100e+02 4.230e+02 6.610e+02
 2.480e+02 7.040e+02 4.120e+02 1.032e+03 2.190e+02 7.080e+02 4.150e+02
 1.004e+03 3.530e+02 7.020e+02 3.690e+02 6.220e+02 2.120e+02 6.450e+02
 8.520e+02 1.150e+03 1.258e+03 2.750e+02 1.760e+02 2.960e+02 5.380e+02
 1.157e+03 4.920e+02 1.198e+03 1.387e+03 5.220e+02 6.580e+02 1.216e+03
 1.480e+03 2.096e+03 1.159e+03 4.400e+02 1.456e+03 8.830e+02 5.470e+02
 7.880e+02 4.850e+02 3.400e+02 1.220e+03 4.270e+02 3.440e+02 7.560e+02
 1.540e+03 6.660e+02 8.030e+02 1.000e+03 8.850e+02 1.386e+03 3.190e+02
 5.340e+02 1.250e+02 1.314e+03 6.020e+02 1.920e+02 5.930e+02 8.040e+02
 1.053e+03 5.320e+02 1.158e+03 1.014e+03 1.940e+02 1.670e+02 7.760e+02
 5.644e+03 6.940e+02 1.572e+03 7.460e+02 1.406e+03 9.250e+02 4.820e+02
 1.890e+02 7.650e+02 8.000e+01 1.443e+03 2.590e+02 7.350e+02 7.340e+02
 1.447e+03 5.480e+02 3.150e+02 1.282e+03 4.080e+02 3.090e+02 2.030e+02
 8.650e+02 2.040e+02 7.900e+02 1.320e+03 7.690e+02 1.070e+03 2.640e+02
 7.590e+02 1.373e+03 9.760e+02 7.810e+02 2.500e+01 1.110e+03 4.040e+02
 5.800e+02 6.780e+02 9.580e+02 1.336e+03 1.079e+03 4.900e+01 8.300e+02
 9.230e+02 7.910e+02 2.630e+02 9.350e+02 1.051e+03 5.140e+02 1.100e+02
 1.414e+03 1.260e+02 1.129e+03 1.298e+03 3.760e+02 4.660e+02 2.440e+02
 1.137e+03 6.870e+02 1.010e+03 1.500e+03 6.700e+02 9.440e+02 1.188e+03
 8.560e+02 3.390e+02 4.810e+02 7.170e+02 5.790e+02 2.740e+02 7.800e+02
 2.830e+02 4.740e+02 4.520e+02 2.760e+02 9.600e+02 7.660e+02 1.026e+03
 7.300e+01 7.360e+02 1.319e+03 2.670e+02 1.092e+03 9.640e+02 9.540e+02
 1.346e+03 1.433e+03 8.700e+02 1.980e+02 1.682e+03 2.380e+02 3.430e+02
 7.600e+01 6.150e+02 7.800e+01 4.200e+01 4.690e+02 2.070e+02 4.580e+02
 4.760e+02 1.341e+03 8.440e+02 8.470e+02 8.500e+02 1.965e+03 7.410e+02
 3.630e+02 2.250e+02 1.333e+03 8.880e+02 6.360e+02 7.260e+02 2.540e+02
 4.350e+02 3.890e+02 2.790e+02 1.360e+03 1.232e+03 2.288e+03 1.531e+03
 1.230e+03 1.015e+03 1.037e+03 1.142e+03 1.262e+03 1.972e+03 8.810e+02
 8.760e+02 2.146e+03 1.557e+03 8.000e+02 6.520e+02 4.940e+02 6.830e+02
 9.130e+02 1.294e+03 2.158e+03 6.820e+02 1.430e+03 7.710e+02 5.400e+01
 5.200e+01 6.800e+01 8.640e+02 1.400e+02 1.733e+03 6.010e+02 9.620e+02
 1.252e+03 1.210e+02 9.550e+02 1.000e+02 1.312e+03 1.720e+02 1.550e+02
 9.310e+02 8.720e+02 7.450e+02 6.210e+02 4.330e+02 8.260e+02 1.340e+02
 1.690e+02 7.490e+02 1.152e+03 5.270e+02 3.420e+02 1.730e+02 7.000e+01
 1.094e+03 8.200e+02 1.021e+03 1.359e+03 7.550e+02 9.500e+02 6.060e+02
 1.259e+03 7.100e+02 1.111e+03 1.478e+03 3.320e+02 7.930e+02 2.460e+02
 1.540e+02 6.500e+01 1.476e+03 5.500e+01 1.758e+03 1.115e+03 1.640e+03
 1.140e+02 7.180e+02 4.960e+02 1.337e+03 1.034e+03 9.830e+02 1.206e+03
 8.900e+02 1.023e+03 1.190e+02 2.860e+02 1.728e+03 1.375e+03 1.420e+03
 2.257e+03 1.149e+03 1.075e+03 3.720e+02 1.204e+03 1.073e+03 1.087e+03
 1.660e+03 1.096e+03 7.290e+02 3.620e+02 5.370e+02 4.720e+02 5.300e+01
 7.640e+02 1.900e+02 1.027e+03 1.141e+03 6.810e+02 8.130e+02 1.280e+02
 1.044e+03 2.600e+02 5.830e+02 3.200e+01 5.310e+02 1.480e+02 7.440e+02
 9.600e+01 5.900e+02 2.000e+02 4.060e+02 1.750e+02 2.010e+02       nan
 7.580e+02 2.210e+02 6.340e+02 1.035e+03 7.790e+02 1.271e+03 3.550e+02
 2.085e+03 7.700e+02 7.220e+02 1.308e+03 6.880e+02 8.800e+01 1.194e+03
 1.538e+03 1.593e+03 1.033e+03 3.660e+02 1.474e+03 1.383e+03 8.930e+02
 1.029e+03 1.223e+03 1.011e+03 1.571e+03 3.180e+02 5.010e+02 7.850e+02
 6.380e+02 6.470e+02 8.380e+02 1.860e+02 9.260e+02 1.101e+03 1.047e+03
 7.970e+02 1.558e+03 1.328e+03 3.140e+02 9.300e+02 7.250e+02 1.151e+03
 1.304e+03 1.812e+03 1.684e+03 6.690e+02 1.178e+03 1.030e+03 8.480e+02
 9.180e+02 5.740e+02 1.181e+03 1.048e+03 3.350e+02 1.225e+03 7.270e+02
 9.680e+02 6.000e+01 9.370e+02 9.010e+02 1.732e+03 1.632e+03 9.730e+02
 9.100e+02 3.460e+02 7.920e+02 6.540e+02 1.300e+02 8.730e+02 9.080e+02
 4.410e+02 8.500e+01 2.420e+02 9.520e+02 1.098e+03 7.820e+02 1.220e+02
 3.160e+02 2.580e+02 5.870e+02 4.910e+02 4.530e+02 5.570e+02 1.080e+03
 4.970e+02 5.100e+01 5.020e+02 6.710e+02 1.412e+03 7.090e+02 1.320e+02
 4.010e+03 4.670e+02 7.700e+01 1.130e+02 5.770e+02 4.340e+02 1.001e+03
 1.392e+03 1.239e+03 9.240e+02 9.490e+02 2.150e+02 1.329e+03 1.112e+03
 7.960e+02 8.110e+02 1.090e+03 5.960e+02 1.127e+03 2.050e+02 1.191e+03
 9.510e+02 3.820e+02 3.730e+02 1.505e+03 1.290e+03 8.800e+02 1.038e+03
 1.182e+03 1.562e+03 1.836e+03 2.780e+02 1.810e+02 1.118e+03 7.600e+02
 7.990e+02 9.960e+02 9.390e+02 9.140e+02 2.710e+02 4.880e+02 7.010e+02
 4.550e+02 8.090e+02 9.530e+02 2.080e+02 1.430e+02 5.760e+02 3.470e+02
 7.940e+02 2.300e+02 2.610e+02 3.930e+02 1.576e+03 1.122e+03 8.530e+02
 4.750e+02 6.910e+02 4.240e+02 3.050e+02 5.260e+02 1.564e+03 9.090e+02
 1.136e+03 1.243e+03 1.490e+02 1.224e+03 3.370e+02]
Os valores únicos: 1
Como é a distribuição:
0.0       929
24.0       27
16.0       14
300.0       9
288.0       8
         ...
383.0       1
1085.0      1
900.0       1
1022.0      1
337.0       1
Name: BsmtFinSF1, Length: 991, dtype: int64

In [129]:
df_completo['BsmtFinSF1'].fillna(0.0, inplace = True)

In [130]:
relatorio(df_completo, 'BsmtFinType2')

Quantidade de valores únicos: 6
Quem são esses valores únicos: ['Unf' 'BLQ' nan 'ALQ' 'Rec' 'LwQ' 'GLQ']
Os valores únicos: 80
Como é a distribuição:
Unf    2493
Rec     105
LwQ      87
BLQ      68
ALQ      52
GLQ      34
Name: BsmtFinType2, dtype: int64

In [131]:
df_completo['BsmtFinType2'].fillna('Unf', inplace = True)

In [133]:
relatorio(df_completo, 'BsmtFinSF2')

Quantidade de valores únicos: 272
Quem são esses valores únicos: [   0.   32.  668.  486.   93.  491.  506.  712.  362.   41.  169.  869.
  150.  670.   28. 1080.  181.  768.  215.  374.  208.  441.  184.  279.
  306.  180.  580.  690.  692.  228.  125. 1063.  620.  175.  820. 1474.
  264.  479.  147.  232.  380.  544.  294.  258.  121.  391.  531.  344.
  539.  713.  210.  311. 1120.  165.  532.   96.  495.  174. 1127.  139.
  202.  645.  123.  551.  219.  606.  612.  480.  182.  132.  336.  468.
  287.   35.  499.  723.  119.   40.  117.  239.   80.  472.   64. 1057.
  127.  630.  128.  377.  764.  345. 1085.  435.  823.  500.  290.  324.
  634.  411.  841. 1061.  466.  396.  354.  149.  193.  273.  465.  400.
  682.  557.  230.  106.  791.  240.  547.  469.  177.  108.  600.  492.
  211.  168. 1031.  438.  375.  144.   81.  906.  608.  276.  661.   68.
  173.  972.  105.  420.  546.  334.  352.  872.  110.  627.  163. 1029.
   78.  859.  981.   42.   46.  162.  350.  263. 1073.   12.  159.  474.
  453.  684.  387.  688.  252.  590.  284.  622.  113. 1526.  360.  774.
  364.  596.  884.   92.  216.  136.  201.  512.  247.  483.  750.   60.
  102.   95.   63.  262.  393.  286.  450.   72.  243.  694.  875.  507.
  419.  250.  116.  624.   76.  270.  288.  186.  449.   48.  613.  852.
  555.  799.  811.  842.  382.  456.  308.   52.  196.  488.  319.   nan
  956.  120.  679.  604.  153.  619.    6.  351. 1037.  829.   38.  206.
  167.  543.  259.  404.  138.  955.  691.   66.  154.  442.  448.  227.
  398.  722.  761.  529.  522.  873.  891.  755.  321.  915.  417.  432.
  831.  278. 1020.  530.  904.  156. 1393. 1039.  497.  402.  748.  281.
  912.  373.  982.  826.  850. 1164. 1083.  337.  297.]
Os valores únicos: 1
Como é a distribuição:
0.0       2571
180.0        5
294.0        5
435.0        3
483.0        3
          ...
600.0        1
211.0        1
1031.0       1
438.0        1
297.0        1
Name: BsmtFinSF2, Length: 272, dtype: int64

In [134]:
df_completo['BsmtFinSF2'].fillna(0.0, inplace = True)

In [136]:
relatorio(df_completo, 'BsmtUnfSF')

Quantidade de valores únicos: 1135
Quem são esses valores únicos: [ 150.  284.  434. ...  129.   45. 1503.]
Os valores únicos: 1
Como é a distribuição:
0.0       241
384.0      19
728.0      14
672.0      13
600.0      12
         ...
257.0       1
1217.0      1
539.0       1
39.0        1
1503.0      1
Name: BsmtUnfSF, Length: 1135, dtype: int64

In [137]:
df_completo['BsmtUnfSF'].fillna(0.0, inplace = True)

In [139]:
relatorio(df_completo, 'TotalBsmtSF')

Quantidade de valores únicos: 1058
Quem são esses valores únicos: [ 856. 1262.  920. ...  498.  432. 1381.]
Os valores únicos: 1
Como é a distribuição:
0.0       78
864.0     74
672.0     29
912.0     26
1040.0    25
          ..
1571.0     1
2633.0     1
757.0      1
873.0      1
1381.0     1
Name: TotalBsmtSF, Length: 1058, dtype: int64

In [140]:
df_completo[df_completo['TotalBsmtSF'].isnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
2120,2121,20,RM,99.0,5940,Pave,IR1,Lvl,AllPub,FR3,Gtl,BrkSide,Feedr,Norm,1Fam,1Story,4,7,1946,1950,Gable,CompShg,MetalSd,CBlock,None,0.0,TA,TA,PConc,TA,TA,No,NaN,0.0,Unf,0.0,0.0,NaN,GasA,TA,Y,FuseA,896,0,0,896,NaN,NaN,1,0,2,1,TA,4,Typ,0,Detchd,1946.0,Unf,1.0,280.0,TA,TA,Y,0,0,0,0,0,0,0,4,2008,ConLD,Abnorml,NaN

In [141]:
df_completo['TotalBsmtSF'].fillna(0.0, inplace = True)

In [142]:
relatorio(df_completo, 'Electrical')

Quantidade de valores únicos: 5
Quem são esses valores únicos: ['SBrkr' 'FuseF' 'FuseA' 'FuseP' 'Mix' nan]
Os valores únicos: 1
Como é a distribuição:
SBrkr    2671
FuseA     188
FuseF      50
FuseP       8
Mix         1
Name: Electrical, dtype: int64

In [143]:
df_completo['Electrical'].fillna('SBrkr', inplace = True)

In [144]:
abacaxi = (df_completo.isnull().sum())
print(abacaxi[abacaxi > 0])

BsmtFinType1      79
BsmtFullBath       2
BsmtHalfBath       2
KitchenQual        1
Functional         2
GarageType       157
GarageYrBlt      159
GarageFinish     159
GarageCars         1
GarageArea         1
GarageQual       159
GarageCond       159
SaleType           1
SalePrice       1459
dtype: int64

In [146]:
relatorio(df_completo, 'BsmtFullBath')

Quantidade de valores únicos: 4
Quem são esses valores únicos: [ 1.  0.  2.  3. nan]
Os valores únicos: 2
Como é a distribuição:
0.0    1705
1.0    1172
2.0      38
3.0       2
Name: BsmtFullBath, dtype: int64

In [147]:
df_completo['BsmtFullBath'].fillna(0.0, inplace = True)

In [149]:
relatorio(df_completo, 'BsmtHalfBath')

Quantidade de valores únicos: 3
Quem são esses valores únicos: [ 0.  1.  2. nan]
Os valores únicos: 2
Como é a distribuição:
0.0    2742
1.0     171
2.0       4
Name: BsmtHalfBath, dtype: int64

In [150]:
df_completo['BsmtHalfBath'].fillna(0.0, inplace = True)

In [152]:
relatorio(df_completo, 'KitchenQual')

Quantidade de valores únicos: 4
Quem são esses valores únicos: ['Gd' 'TA' 'Ex' 'Fa' nan]
Os valores únicos: 1
Como é a distribuição:
TA    1492
Gd    1151
Ex     205
Fa      70
Name: KitchenQual, dtype: int64

In [153]:
df_completo['KitchenQual'].fillna('TA', inplace = True)

In [154]:
#Functional         2

In [155]:
relatorio(df_completo, 'Functional')

Quantidade de valores únicos: 7
Quem são esses valores únicos: ['Typ' 'Min1' 'Maj1' 'Min2' 'Mod' 'Maj2' 'Sev' nan]
Os valores únicos: 2
Como é a distribuição:
Typ     2717
Min2      70
Min1      65
Mod       35
Maj1      19
Maj2       9
Sev        2
Name: Functional, dtype: int64

In [156]:
df_completo['Functional'].fillna('Typ', inplace = True)

In [157]:
banana = (df_completo.isnull().sum())
print(banana[ banana > 0])

BsmtFinType1      79
GarageType       157
GarageYrBlt      159
GarageFinish     159
GarageCars         1
GarageArea         1
GarageQual       159
GarageCond       159
SaleType           1
SalePrice       1459
dtype: int64

In [158]:
relatorio( df_completo, 'GarageType' )

Quantidade de valores únicos: 6
Quem são esses valores únicos: ['Attchd' 'Detchd' 'BuiltIn' 'CarPort' nan 'Basment' '2Types']
Os valores únicos: 157
Como é a distribuição:
Attchd     1723
Detchd      779
BuiltIn     186
Basment      36
2Types       23
CarPort      15
Name: GarageType, dtype: int64

In [170]:
coluna_a = ['Attchd', 'Detchd', 'BuiltIn', 'CarPort', 'Basment', '2Types']

In [174]:
df_completo[(df_completo['GarageType'] != 'Attchd') & (df_completo['GarageType'] != 'Detchd') & (df_completo['GarageType'] != 'BuiltIn') & (df_completo['GarageType'] != 'CarPort') & (df_completo['GarageType'] != 'Basment') & (df_completo['GarageType'] != '2Types')]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
39,40,90,RL,65.0,6040,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,Duplex,1Story,4,5,1955,1955,Gable,CompShg,AsbShng,Plywood,None,0.0,TA,TA,PConc,TA,TA,No,NaN,0.0,Unf,0.0,0.0,0.0,GasA,TA,N,FuseP,1152,0,0,1152,0.0,0.0,2,0,2,2,Fa,6,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,0,0,0,0,0,6,2008,WD,AdjLand,82000.0
48,49,190,RM,33.0,4456,Pave,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,2fmCon,2Story,4,5,1920,2008,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,BrkTil,TA,TA,No,Unf,0.0,Unf,0.0,736.0,736.0,GasA,Gd,Y,SBrkr,736,716,0,1452,0.0,0.0,2,0,2,3,TA,8,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,102,0,0,0,0,6,2009,New,Partial,113000.0
78,79,90,RL,72.0,10778,Pave,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,Norm,Norm,Duplex,1Story,4,5,1968,1968,Hip,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,CBlock,TA,TA,No,Unf,0.0,Unf,0.0,1768.0,1768.0,GasA,TA,N,SBrkr,1768,0,0,1768,0.0,0.0,2,0,4,2,TA,8,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,0,0,0,0,0,0,4,2010,WD,Normal,136500.0
88,89,50,C (all),105.0,8470,Pave,IR1,Lvl,AllPub,Corner,Gtl,IDOTRR,Feedr,Feedr,1Fam,1.5Fin,3,2,1915,1982,Hip,CompShg,Plywood,Plywood,None,0.0,Fa,Fa,CBlock,TA,Fa,No,Unf,0.0,Unf,0.0,1013.0,1013.0,GasA,TA,N,SBrkr,1013,0,513,1526,0.0,0.0,1,0,2,1,Fa,6,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,156,0,0,0,0,10,2009,ConLD,Abnorml,85000.0
89,90,20,RL,60.0,8070,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,1Story,4,5,1994,1995,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,No,GLQ,588.0,Unf,0.0,402.0,990.0,GasA,Ex,Y,SBrkr,990,0,0,990,1.0,0.0,1,0,3,1,TA,5,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,0,0,0,0,0,0,8,2007,WD,Normal,123600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2893,2894,50,C (all),60.0,8520,Grvl,Reg,Bnk,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,1.5Fin,3,5,1916,1950,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,PConc,Fa,Fa,No,Unf,0.0,Unf,0.0,216.0,216.0,GasA,Fa,N,SBrkr,576,360,0,936,0.0,0.0,1,0,2,1,TA,6,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,0,0,0,0,0,4,2006,WD,Normal,NaN
2909,2910,180,RM,21.0,1470,Pave,Reg,Lvl,AllPub,Inside,Gtl,MeadowV,Norm,Norm,Twnhs,SFoyer,4,6,1970,1970,Gable,CompShg,CemntBd,CmentBd,None,0.0,TA,TA,CBlock,Gd,TA,Av,GLQ,522.0,Unf,0.0,108.0,630.0,GasA,TA,Y,SBrkr,630,0,0,630,1.0,0.0,1,0,1,1,TA,3,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,0,0,0,0,0,0,4,2006,WD,Normal,NaN
2913,2914,160,RM,21.0,1526,Pave,Reg,Lvl,AllPub,Inside,Gtl,MeadowV,Norm,Norm,Twnhs,2Story,4,5,1970,1970,Gable,CompShg,CemntBd,CmentBd,None,0.0,TA,TA,CBlock,TA,TA,No,Unf,0.0,Unf,0.0,546.0,546.0,GasA,TA,Y,SBrkr,546,546,0,1092,0.0,0.0,1,1,3,1,TA,5,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,34,0,0,0,0,0,6,2006,WD,Normal,NaN
2914,2915,160,RM,21.0,1936,Pave,Reg,Lvl,AllPub,Inside,Gtl,MeadowV,Norm,Norm,Twnhs,2Story,4,7,1970,1970,Gable,CompShg,CemntBd,CmentBd,None,0.0,TA,TA,CBlock,TA,TA,No,Unf,0.0,Unf,0.0,546.0,546.0,GasA,Gd,Y,SBrkr,546,546,0,1092,0.0,0.0,1,1,3,1,TA,5,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,0,0,0,0,0,0,6,2006,WD,Normal,NaN
2917,2918,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,SFoyer,5,5,1992,1992,Gable,CompShg,HdBoard,Wd Shng,None,0.0,TA,TA,PConc,Gd,TA,Av,GLQ,337.0,Unf,0.0,575.0,912.0,GasA,TA,Y,SBrkr,970,0,0,970,0.0,1.0,1,0,3,1,TA,6,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,80,32,0,0,0,0,700,7,2006,WD,Normal,NaN

In [175]:
df_completo[~df_completo['GarageType'].isin(['Attchd', 'Detchd', 'BuiltIn', 'CarPort', 'Basment', '2Types'])]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
39,40,90,RL,65.0,6040,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,Duplex,1Story,4,5,1955,1955,Gable,CompShg,AsbShng,Plywood,None,0.0,TA,TA,PConc,TA,TA,No,NaN,0.0,Unf,0.0,0.0,0.0,GasA,TA,N,FuseP,1152,0,0,1152,0.0,0.0,2,0,2,2,Fa,6,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,0,0,0,0,0,6,2008,WD,AdjLand,82000.0
48,49,190,RM,33.0,4456,Pave,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,2fmCon,2Story,4,5,1920,2008,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,BrkTil,TA,TA,No,Unf,0.0,Unf,0.0,736.0,736.0,GasA,Gd,Y,SBrkr,736,716,0,1452,0.0,0.0,2,0,2,3,TA,8,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,102,0,0,0,0,6,2009,New,Partial,113000.0
78,79,90,RL,72.0,10778,Pave,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,Norm,Norm,Duplex,1Story,4,5,1968,1968,Hip,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,CBlock,TA,TA,No,Unf,0.0,Unf,0.0,1768.0,1768.0,GasA,TA,N,SBrkr,1768,0,0,1768,0.0,0.0,2,0,4,2,TA,8,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,0,0,0,0,0,0,4,2010,WD,Normal,136500.0
88,89,50,C (all),105.0,8470,Pave,IR1,Lvl,AllPub,Corner,Gtl,IDOTRR,Feedr,Feedr,1Fam,1.5Fin,3,2,1915,1982,Hip,CompShg,Plywood,Plywood,None,0.0,Fa,Fa,CBlock,TA,Fa,No,Unf,0.0,Unf,0.0,1013.0,1013.0,GasA,TA,N,SBrkr,1013,0,513,1526,0.0,0.0,1,0,2,1,Fa,6,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,156,0,0,0,0,10,2009,ConLD,Abnorml,85000.0
89,90,20,RL,60.0,8070,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,1Story,4,5,1994,1995,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,No,GLQ,588.0,Unf,0.0,402.0,990.0,GasA,Ex,Y,SBrkr,990,0,0,990,1.0,0.0,1,0,3,1,TA,5,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,0,0,0,0,0,0,8,2007,WD,Normal,123600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2893,2894,50,C (all),60.0,8520,Grvl,Reg,Bnk,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,1.5Fin,3,5,1916,1950,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,PConc,Fa,Fa,No,Unf,0.0,Unf,0.0,216.0,216.0,GasA,Fa,N,SBrkr,576,360,0,936,0.0,0.0,1,0,2,1,TA,6,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,N,0,0,0,0,0,0,0,4,2006,WD,Normal,NaN
2909,2910,180,RM,21.0,1470,Pave,Reg,Lvl,AllPub,Inside,Gtl,MeadowV,Norm,Norm,Twnhs,SFoyer,4,6,1970,1970,Gable,CompShg,CemntBd,CmentBd,None,0.0,TA,TA,CBlock,Gd,TA,Av,GLQ,522.0,Unf,0.0,108.0,630.0,GasA,TA,Y,SBrkr,630,0,0,630,1.0,0.0,1,0,1,1,TA,3,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,0,0,0,0,0,0,4,2006,WD,Normal,NaN
2913,2914,160,RM,21.0,1526,Pave,Reg,Lvl,AllPub,Inside,Gtl,MeadowV,Norm,Norm,Twnhs,2Story,4,5,1970,1970,Gable,CompShg,CemntBd,CmentBd,None,0.0,TA,TA,CBlock,TA,TA,No,Unf,0.0,Unf,0.0,546.0,546.0,GasA,TA,Y,SBrkr,546,546,0,1092,0.0,0.0,1,1,3,1,TA,5,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,34,0,0,0,0,0,6,2006,WD,Normal,NaN
2914,2915,160,RM,21.0,1936,Pave,Reg,Lvl,AllPub,Inside,Gtl,MeadowV,Norm,Norm,Twnhs,2Story,4,7,1970,1970,Gable,CompShg,CemntBd,CmentBd,None,0.0,TA,TA,CBlock,TA,TA,No,Unf,0.0,Unf,0.0,546.0,546.0,GasA,Gd,Y,SBrkr,546,546,0,1092,0.0,0.0,1,1,3,1,TA,5,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,0,0,0,0,0,0,0,6,2006,WD,Normal,NaN
2917,2918,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,SFoyer,5,5,1992,1992,Gable,CompShg,HdBoard,Wd Shng,None,0.0,TA,TA,PConc,Gd,TA,Av,GLQ,337.0,Unf,0.0,575.0,912.0,GasA,TA,Y,SBrkr,970,0,0,970,0.0,1.0,1,0,3,1,TA,6,Typ,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,Y,80,32,0,0,0,0,700,7,2006,WD,Normal,NaN

In [ ]:
#na linha de código acima, ao inves de ficar copiando e colocando a formula " & (df_completo['GarageType'] != 'BuiltIn')" para cada uma das respostas
#eu achei uma solução no https://stackoverflow.com/questions/34397982/access-multiple-items-with-not-equal-to
#Onde apresenteva o mesmo resultado mas usando o "isin" e "~"

In [176]:
#o isin retorna os valores que forem apresentados dentro da lista (['', '', ''])
#mas colocando o "~" antes da filtram, o sinal inverte a função isin, ou seja, retornará apenas os valores que NÃO estão na lista

In [60]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import model_selection, tree, preprocessing, metrics, linear_model
from sklearn.svm import LinearSVC
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LinearRegression, LogisticRegression, SGDClassifier
from sklearn.tree import DecisionTreeClassifier
!pip install catboost
import catboost
from catboost import CatBoostClassifier, Pool, cv

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: catboost in /usr/local/lib/python3.7/dist-packages (1.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.21.6)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (5.5.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.7.3)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2022.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (3.0.9)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib->catboost) (4.1.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (8.1.0)